name: tailscale

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

permissions:
  id-token: write # This is required for the Tailscale action to request a JWT from GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Tailscale Action
        uses: tailscale/github-action@main
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          audience: ${{ secrets.TS_AUDIENCE }}
          tags: tag:actions
          version: 1.98.4
          statedir: /tmp/tailscale-state/
          use-cache: 'true'

      - name: bug report
        run: tailscale bugreport

      - name: store ip in env
        run:
          echo "TS_IP=$(tailscale ip -4)" >> $GITHUB_ENV

      - name: retrieve env
        run: |
          echo "The value of TS_IP is $TS_IP"

      - name: run curl
        run: |
          curl -vvv http://100.91.37.103

      - name: logout
        run: |
          sudo tailscale logout
