name: tailscale

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Tailscale Action
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}
          tags: tag:container
          version: 1.88.3
          statedir: /tmp/tailscale-state/
          use-cache: 'true'

      - name: bug report
        run: tailscale bugreport

      - name: store ip in env
        run:
          echo "TS_IP=$(tailscale ip -4)" >> $GITHUB_ENV

      - name: retrieve env
        run: |
          echo "The value of TS_IP is $TS_IP"

      - name: run curl
        run: |
          curl -vvv http://100.116.116.54
