name: tailscale

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: create directory
        run: mkdir -p /tmp/tailscale-tmp

      - name: Tailscale Action
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tailscaled-args: --statedir=/tmp/tailscale-tmp
          tags: tag:actions
          version: 1.42.0

      - name: store ip in env
        run:
          echo "TS_IP=$(tailscale ip -4)" >> $GITHUB_ENV

      - name: retrieve env
        run: |
          echo "The value of TS_IP is $TS_IP"

          
      - name: run curl
        run: |
          curl -vvv http://100.116.116.54
